version: "3"
services:
  web:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ${PWD}/nginx:/etc/nginx/conf.d
      - ${PWD}/Braizerecords:/var/www/Braizerecords
    links:
      - php
      - mysql
      - maildev

  php:
    build: php
    restart: always
    volumes:
      - ${PWD}/Braizerecords:/var/www/Braizerecords
    links:
      - mysql
      - maildev

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=root
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    volumes: 
      - ${PWD}/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    container_name: phpmyadmin
    ports:
      - "8080:80"
    restart: always
    environment:
      - PMA_USER=root
      - PMA_PASSWORD=root
      - PMA_HOST=mysql



  maildev:
    image: djfarrelly/maildev
    ports:
      - "1081:81"
      - "1025:25"

